### ISSUE TITLE
app - search double click issue

### ISSUE THREAD

**Issue by dajposkakac** [dajposkakac/CO600_TransportProject#1]
```
03-24 02:29:19.376 24330-24434/com.tvshowfavs W/GoogleAnalyticsTracker: Problem with socket or streams.
                                                                        java.net.ConnectException: failed to connect to www.google-analytics.com/127.0.0.1 (port 80): connect failed: ECONNREFUSED (Connection refused)
                                                                            at libcore.io.IoBridge.connect(IoBridge.java:124)
                                                                            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                            at java.net.Socket.connect(Socket.java:884)
                                                                            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
                                                                            at com.google.android.apps.analytics.PipelinedRequester.maybeOpenConnection(Unknown Source)
                                                                            at com.google.android.apps.analytics.PipelinedRequester.addRequest(Unknown Source)
                                                                            at com.google.android.apps.analytics.NetworkDispatcher$DispatcherThread$AsyncDispatchTask.dispatchSomePendingHits(Unknown Source)
                                                                            at com.google.android.apps.analytics.NetworkDispatcher$DispatcherThread$AsyncDispatchTask.run(Unknown Source)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                         Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
                                                                            at libcore.io.Posix.connect(Native Method)
                                                                            at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
                                                                            at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
                                                                            at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
                                                                            at java.net.Socket.connect(Socket.java:884) 
                                                                            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124) 
                                                                            at com.google.android.apps.analytics.PipelinedRequester.maybeOpenConnection(Unknown Source) 
                                                                            at com.google.android.apps.analytics.PipelinedRequester.addRequest(Unknown Source) 
                                                                            at com.google.android.apps.analytics.NetworkDispatcher$DispatcherThread$AsyncDispatchTask.dispatchSomePendingHits(Unknown Source) 
                                                                            at com.google.android.apps.analytics.NetworkDispatcher$DispatcherThread$AsyncDispatchTask.run(Unknown Source) 
                                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
```

possibly connected??

**Comment by dajposkakac** [comment]
wifi issue?

**Comment by dajposkakac** [comment]
seems to be caused by running the server on the same network as the client
